version: '3.8'

services:

  auth-db:
    image: postgres
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    env_file:
      - .env.db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_AUTH_DB}
    ports:
      - "5433:5432"

  auth-api:
    build: ./services/auth
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./services/auth:/code
    ports:
      - "8002:80"
    env_file:
      - .env.db
      - .env.web
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_AUTH_DB}
      - POSTGRES_HOST=auth-db
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-db

volumes:
  auth-db-data: